title: Pendata
author: Dhafin Rizqika Akhmad

execute:
  execute_notebooks: off

html:
  use_repository_button: true

repository:
  url: https://github.com/dapinfru/pendata
  branch: main

launch_buttons:
  colab_url: https://colab.research.google.com/github/dapinfru/pendata/blob/main
  binderhub_url: https://mybinder.org/v2/gh/dapinfru/pendata/main